# Generated by Django 2.0.1 on 2018-01-17 12:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='name')),
            ],
            options={
                'verbose_name': 'datasource',
                'verbose_name_plural': 'datasources',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='location')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('parameter', models.CharField(max_length=100, verbose_name='parameter')),
                ('value', models.FloatField(verbose_name='value')),
                ('unit', models.CharField(max_length=40, verbose_name='unit')),
                ('source', models.CharField(blank=True, max_length=40, null=True, verbose_name='source')),
            ],
            options={
                'verbose_name': 'measurement',
                'verbose_name_plural': 'measurements',
            },
        ),
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('parameter', models.CharField(max_length=100, verbose_name='parameter')),
                ('sourceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Datasource', verbose_name='datasource')),
            ],
            options={
                'verbose_name': 'Timeseries',
                'verbose_name_plural': 'Timeseries',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.FloatField(default=1, verbose_name='scale')),
                ('offset', models.FloatField(default=0, verbose_name='offset')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='data.Unit', verbose_name='source')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='data.Unit', verbose_name='target')),
            ],
            options={
                'verbose_name': 'Unit conversion',
                'verbose_name_plural': 'Unit conversions',
            },
        ),
        migrations.AddField(
            model_name='timeseries',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Unit', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Timeseries', verbose_name='timeseries'),
        ),
    ]
